<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<VersionPrefix>1.0.2</VersionPrefix>
	<AssemblyVersion>$(VersionPrefix)</AssemblyVersion>
	<FileVersion>$(VersionPrefix)</FileVersion>
	<NeutralLanguage>en</NeutralLanguage>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	<IsPackable>true</IsPackable>
	<Title>Serverless Workflow SDK - IO</Title>
	<Description>Contains services used to read and write ServerlessWorkflow workflow definitions</Description>
	<PackageTags>serverless-workflow;serverless;workflow;dsl;sdk;io</PackageTags>
	<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
	<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<Copyright>Copyright © 2024-Present The Serverless Workflow Authors. All rights reserved.</Copyright>
	<PackageProjectUrl>https://github.com/serverlessworkflow/sdk-net</PackageProjectUrl>
	<RepositoryUrl>https://github.com/serverlessworkflow/sdk-net</RepositoryUrl>
	<RepositoryType>git</RepositoryType>
	<DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
	<PackageReference Include="Yaml2JsonNode" Version="3.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServerlessWorkflow.Sdk\ServerlessWorkflow.Sdk.csproj" />
  </ItemGroup>
	
  <ItemGroup>
    <None Include="..\..\README.md" Link="README.md">
      <PackagePath>\</PackagePath>
      <Pack>True</Pack>
    </None>
  </ItemGroup>

</Project>
