namespace ServerlessWorkflow.Sdk.Serialization.Json;

/// <summary>
/// Represents the JSON serialization context for the Serverless Workflow SDK, providing configuration and metadata for serializing and deserializing all relevant types within the SDK to and from JSON format.
/// </summary>
[JsonSourceGenerationOptions(DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(AsyncApiCallDefinition))]
[JsonSerializable(typeof(AsyncApiMessageDefinition))]
[JsonSerializable(typeof(AsyncApiSubscriptionDefinition))]
[JsonSerializable(typeof(AsyncApiSubscriptionLifetimeDefinition))]
[JsonSerializable(typeof(AuthenticationPolicyDefinition))]
[JsonSerializable(typeof(AuthenticationSchemeDefinition))]
[JsonSerializable(typeof(BackoffDefinition))]
[JsonSerializable(typeof(BackoffStrategyDefinition))]
[JsonSerializable(typeof(BasicAuthenticationSchemeDefinition))]
[JsonSerializable(typeof(BearerAuthenticationSchemeDefinition))]
[JsonSerializable(typeof(BranchingDefinition))]
[JsonSerializable(typeof(CatalogDefinition))]
[JsonSerializable(typeof(CallTaskDefinition))]
[JsonSerializable(typeof(CertificateAuthenticationSchemeDefinition))]
[JsonSerializable(typeof(ComponentDefinition))]
[JsonSerializable(typeof(ComponentDefinitionCollection))]
[JsonSerializable(typeof(ContainerLifetimeDefinition))]
[JsonSerializable(typeof(ContainerProcessDefinition))]
[JsonSerializable(typeof(ConstantBackoffDefinition))]
[JsonSerializable(typeof(CorrelationKeyDefinition))]
[JsonSerializable(typeof(DateTimeDescriptor))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(DigestAuthenticationSchemeDefinition))]
[JsonSerializable(typeof(DoTaskDefinition))]
[JsonSerializable(typeof(Duration))]
[JsonSerializable(typeof(EmitTaskDefinition))]
[JsonSerializable(typeof(EndpointDefinition))]
[JsonSerializable(typeof(Epoch))]
[JsonSerializable(typeof(Error))]
[JsonSerializable(typeof(ErrorCatcherDefinition))]
[JsonSerializable(typeof(ErrorDefinition))]
[JsonSerializable(typeof(ErrorFilterDefinition))]
[JsonSerializable(typeof(EventConsumptionStrategyDefinition))]
[JsonSerializable(typeof(EventDefinition))]
[JsonSerializable(typeof(EventEmissionDefinition))]
[JsonSerializable(typeof(EventFilterDefinition))]
[JsonSerializable(typeof(ExponentialBackoffDefinition))]
[JsonSerializable(typeof(ExtensionDefinition))]
[JsonSerializable(typeof(ExtensionTaskDefinition))]
[JsonSerializable(typeof(ExternalResourceDefinition))]
[JsonSerializable(typeof(ForkTaskDefinition))]
[JsonSerializable(typeof(ForLoopDefinition))]
[JsonSerializable(typeof(ForTaskDefinition))]
[JsonSerializable(typeof(GrpcCallDefinition))]
[JsonSerializable(typeof(GrpcServiceDefinition))]
[JsonSerializable(typeof(HttpCallDefinition))]
[JsonSerializable(typeof(HttpRequest))]
[JsonSerializable(typeof(HttpResponse))]
[JsonSerializable(typeof(IDictionary<string, SwitchCaseDefinition>))]
[JsonSerializable(typeof(IDictionary<string, TaskDefinition>))]
[JsonSerializable(typeof(InputDataModelDefinition))]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(JitterDefinition))]
[JsonSerializable(typeof(JsonArray))]
[JsonSerializable(typeof(JsonNode))]
[JsonSerializable(typeof(JsonObject))]
[JsonSerializable(typeof(JsonValue))]
[JsonSerializable(typeof(LinearBackoffDefinition))]
[JsonSerializable(typeof(ListenerDefinition))]
[JsonSerializable(typeof(ListenTaskDefinition))]
[JsonSerializable(typeof(OAuth2AuthenticationClientDefinition))]
[JsonSerializable(typeof(OAuth2AuthenticationEndpointsDefinition))]
[JsonSerializable(typeof(OAuth2AuthenticationRequestDefinition))]
[JsonSerializable(typeof(OAuth2AuthenticationSchemeDefinition))]
[JsonSerializable(typeof(OAuth2AuthenticationSchemeDefinitionBase))]
[JsonSerializable(typeof(OAuth2TokenDefinition))]
[JsonSerializable(typeof(OpenApiCallDefinition))]
[JsonSerializable(typeof(OpenIDConnectSchemeDefinition))]
[JsonSerializable(typeof(OutputDataModelDefinition))]
[JsonSerializable(typeof(ProcessDefinition))]
[JsonSerializable(typeof(ProcessTypeDefinition))]
[JsonSerializable(typeof(RaiseErrorDefinition))]
[JsonSerializable(typeof(RaiseTaskDefinition))]
[JsonSerializable(typeof(ReferenceableComponentDefinition))]
[JsonSerializable(typeof(RetryAttemptLimitDefinition))]
[JsonSerializable(typeof(RetryingTaskEvent))]
[JsonSerializable(typeof(RetryPolicyDefinition))]
[JsonSerializable(typeof(RetryPolicyLimitDefinition))]
[JsonSerializable(typeof(RunTaskDefinition))]
[JsonSerializable(typeof(RuntimeDescriptor))]
[JsonSerializable(typeof(RuntimeExpressionEvaluationConfiguration))]
[JsonSerializable(typeof(SchemaDefinition))]
[JsonSerializable(typeof(ScriptProcessDefinition))]
[JsonSerializable(typeof(SetTaskDefinition))]
[JsonSerializable(typeof(ShellProcessDefinition))]
[JsonSerializable(typeof(SubscriptionIteratorDefinition))]
[JsonSerializable(typeof(SwitchCaseDefinition))]
[JsonSerializable(typeof(SwitchTaskDefinition))]
[JsonSerializable(typeof(TaskCancelledEvent))]
[JsonSerializable(typeof(TaskCompletedEvent))]
[JsonSerializable(typeof(TaskCreatedEvent))]
[JsonSerializable(typeof(TaskEndedEvent))]
[JsonSerializable(typeof(TaskFaultedEvent))]
[JsonSerializable(typeof(TaskResumedEvent))]
[JsonSerializable(typeof(TaskSkippedEvent))]
[JsonSerializable(typeof(TaskStartedEvent))]
[JsonSerializable(typeof(TaskSuspendedEvent))]
[JsonSerializable(typeof(TaskDefinition))]
[JsonSerializable(typeof(TaskDescriptor))]
[JsonSerializable(typeof(TimeoutDefinition))]
[JsonSerializable(typeof(TryTaskDefinition))]
[JsonSerializable(typeof(WaitTaskDefinition))]
[JsonSerializable(typeof(WorkflowCancelledEvent))]
[JsonSerializable(typeof(WorkflowCompletedEvent))]
[JsonSerializable(typeof(WorkflowCorrelationCompletedEvent))]
[JsonSerializable(typeof(WorkflowCorrelationStartedEvent))]
[JsonSerializable(typeof(WorkflowDefinition))]
[JsonSerializable(typeof(WorkflowEndedEvent))]
[JsonSerializable(typeof(WorkflowFaultedEvent))]
[JsonSerializable(typeof(WorkflowResumedEvent))]
[JsonSerializable(typeof(WorkflowStartedEvent))]
[JsonSerializable(typeof(WorkflowSuspendedEvent))]
[JsonSerializable(typeof(WorkflowDefinitionMetadata))]
[JsonSerializable(typeof(WorkflowDefinitionReference))]
[JsonSerializable(typeof(WorkflowDescriptor))]
[JsonSerializable(typeof(WorkflowProcessDefinition))]
[JsonSerializable(typeof(WorkflowScheduleDefinition))]
public partial class JsonSerializationContext
    : JsonSerializerContext
{



}
