<Project Sdk="Microsoft.NET.Sdk">

 <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<RootNamespace>ServerlessWorkflow.Sdk.Runtime</RootNamespace>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="KubernetesClient" Version="19.0.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServerlessWorkflow.Sdk.Runtime.Abstractions\ServerlessWorkflow.Sdk.Runtime.Abstractions.csproj" />
  </ItemGroup>

</Project>
