<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
	<LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	<VersionPrefix>1.0.2</VersionPrefix>
	<AssemblyVersion>$(VersionPrefix)</AssemblyVersion>
	<FileVersion>$(VersionPrefix)</FileVersion>
	<NeutralLanguage>en</NeutralLanguage>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	<IsPackable>true</IsPackable>
	<Title>Serverless Workflow SDK</Title>
	<Description>Contains Serverless Workflow DSL models</Description>
	<PackageTags>serverless-workflow;serverless;workflow;dsl;sdk</PackageTags>
	<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
	<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
	<PackageReadmeFile>readme.md</PackageReadmeFile>
	<Copyright>Copyright © 2024-Present The Serverless Workflow Authors. All rights reserved.</Copyright>
	<PackageProjectUrl>https://github.com/serverlessworkflow/sdk-net</PackageProjectUrl>
	<RepositoryUrl>https://github.com/serverlessworkflow/sdk-net</RepositoryUrl>
	<RepositoryType>git</RepositoryType>
	<DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JsonPatch.Net" Version="5.0.2" />
    <PackageReference Include="JsonSchema.Net" Version="9.1.4" />
    <PackageReference Include="Microsoft.Bcl.HashCode" Version="6.0.0" />
    <PackageReference Include="System.Text.Json" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
	
</Project>
