name: Build .NET

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - '**/*.md'
      - 'assets/**'
      - 'deployments/**'
  workflow_call:

env:
  SOLUTION: ./ServerlessWorkflow.Sdk.sln

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Pull latest version tag
        if: github.event_name != 'pull_request'
        run: |
          git fetch
          git pull

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Restore dependencies
        run: dotnet restore "${{ env.SOLUTION }}"

      - name: Build
        run: dotnet build "${{ env.SOLUTION }}" --configuration Release --no-restore
      
      - name: Cache build items
        if: github.event_name != 'pull_request'
        uses: actions/cache@v3
        id: build-dotnet-cache
        with:
          path: ./**/Release/*.nupkg
          key: build-dotnet-cache-${{ github.sha }}
