name: Test .NET

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - '**/*.md'
      - 'assets/**'
      - 'deployments/**'
  workflow_call:

env:
  SOLUTION: ./ServerlessWorkflow.Sdk.sln

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Restore dependencies
        run: dotnet restore "${{ env.SOLUTION }}"

      # - name: Test
      #   run: dotnet test "${{ env.SOLUTION }}" --no-restore --verbosity normal"

      # Test "per domain" for ease of readability
      - name: Test Core
        run: dotnet test "${{ env.SOLUTION }}" --no-restore --filter "FullyQualifiedName~Cases.Core"
      # ...
